-- Initial schema: users, projects, deployments, logs.
--
-- Replaces Hibernate's ddl-auto, which could not express renames or drops and
-- produced a schema that depended on whatever the database looked like before.
-- From here the schema is versioned SQL: reviewable in a pull request, applied
-- exactly once, and identical in every environment.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL,
    email         VARCHAR(255) NOT NULL,
    -- Named password_hash rather than password so the invariant is visible in
    -- the schema itself: a plaintext password must never be stored here.
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'DEVELOPER', 'VIEWER'))
);

-- Unique constraints get explicit names. Hibernate generated things like
-- uk6dotkott2kjsp8vw4d0m25fb7, which tells nobody anything when it surfaces in
-- a constraint violation.
CREATE UNIQUE INDEX uk_users_email ON users (email);
CREATE UNIQUE INDEX uk_users_username ON users (username);

CREATE TABLE projects (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    created_by  BIGINT       NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_projects_created_by FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE UNIQUE INDEX uk_projects_name ON projects (name);

-- Postgres does NOT index foreign keys automatically. Every ownership check
-- resolves a project's creator, so without this each one is a sequential scan
-- of users.
CREATE INDEX ix_projects_created_by ON projects (created_by);

CREATE TABLE deployments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id   BIGINT      NOT NULL,
    version      VARCHAR(50) NOT NULL,
    environment  VARCHAR(20) NOT NULL,
    status       VARCHAR(20) NOT NULL,
    deployed_by  BIGINT      NOT NULL,
    started_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    -- Null while IN_PROGRESS; set exactly once when the deployment settles.
    completed_at TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT fk_deployments_project FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_deployments_deployed_by FOREIGN KEY (deployed_by) REFERENCES users (id),
    CONSTRAINT ck_deployments_environment CHECK (environment IN ('DEV', 'STAGING', 'PRODUCTION')),
    CONSTRAINT ck_deployments_status CHECK (status IN ('IN_PROGRESS', 'SUCCESS', 'FAILED'))
);

-- Deployment history is always read newest-first for one project, so the index
-- carries the sort order rather than making Postgres sort afterwards.
CREATE INDEX ix_deployments_project_started ON deployments (project_id, started_at DESC);

-- Backs the concurrency guard, which asks whether an IN_PROGRESS deployment
-- already exists for a project and environment on every trigger.
CREATE INDEX ix_deployments_project_env_status ON deployments (project_id, environment, status);

CREATE INDEX ix_deployments_deployed_by ON deployments (deployed_by);

CREATE TABLE logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deployment_id BIGINT      NOT NULL,
    level         VARCHAR(10) NOT NULL,
    -- TEXT rather than VARCHAR(n): log lines include stack traces, and a length
    -- limit would truncate exactly the messages worth reading.
    message       TEXT        NOT NULL,
    timestamp     TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_logs_deployment FOREIGN KEY (deployment_id) REFERENCES deployments (id),
    CONSTRAINT ck_logs_level CHECK (level IN ('DEBUG', 'INFO', 'WARN', 'ERROR'))
);

-- The fastest-growing table in the system, and always queried by deployment in
-- timestamp order. Without this index, reading one deployment's logs scans
-- every log row ever written.
CREATE INDEX ix_logs_deployment_timestamp ON logs (deployment_id, timestamp, id);

CREATE INDEX ix_logs_deployment_level ON logs (deployment_id, level);
